# Generated by Django 4.0.2 on 2022-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='prichina',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='posetil',
            new_name='visited',
        ),
    ]
