# Generated by Django 4.0.2 on 2022-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visits',
            name='time_end',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='time_start',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
