# Generated by Django 4.0.2 on 2022-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_alter_visits_reason_alter_visits_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='visited',
            field=models.BooleanField(choices=[(True, 'Посетил(а)'), (False, 'Не посетил(а)')]),
        ),
    ]
