# Generated by Django 4.0.2 on 2022-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='steck',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
